### ISSUE TITLE
roborock.vacuum.s5/firmware forbidden error 403

### ISSUE THREAD

**Issue by rumpeltux** [dgiese/dustcloud-documentation#2]
https://github.com/dgiese/dustcloud-documentation/tree/master/roborock.vacuum.s5/firmware points to https://dustcloud.seemoo.de/public/xiaomi.vacuum.gen2 which only yields a 403.

**Comment by sedrubal** [comment]
Same issue with <https://github.com/dgiese/dustcloud-documentation/tree/master/rockrobo.vacuum.v1/firmware> for gen1:
<https://dustcloud.seemoo.de/public/xiaomi.vacuum.gen1>

**Comment by dgiese** [comment]
All the links have been moved to https://builder.dontvacuum.me/pkg
